FROM public.ecr.aws/docker/library/node:18.19.1

ARG https_proxy
ARG http_proxy
ARG socks_proxy
ARG no_proxy
ENV LANG=en_US.UTF-8
ENV https_proxy=${https_proxy}
ENV http_proxy=${http_proxy}
ENV socks_proxy=${socks_proxy}
ENV no_proxy=${no_proxy}
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone && \
echo "export LS_OPTIONS='--color=auto'" >> /root/.bashrc && echo "alias ls='ls \$LS_OPTIONS'" >> /root/.bashrc && echo "alias ll='ls \$LS_OPTIONS -l'" >> /root/.bashrc && \
 apt update && \
apt-get install -y nginx
RUN rm -f /etc/nginx/sites-enabled/default
ADD ./docker-compose/nginx-web.conf /etc/nginx/conf.d/
ADD ./docker-compose/ssl /etc/nginx/ssl/

WORKDIR /opt
ADD openikt-web/dist/index.html ./openikt-web/dist/
ADD openikt-web/dist ./openikt-web/dist/openikt/
ENV https_proxy=
ENV http_proxy=

CMD []
